export enum ErrorCode {
  // General Errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  CONFLICT = 'CONFLICT',

  // OAuth & Authentication Errors
  OAUTH_UNAUTHORIZED = 'OAUTH_UNAUTHORIZED',
  OAUTH_INVALID_TOKEN = 'OAUTH_INVALID_TOKEN',
  OAUTH_TOKEN_EXPIRED = 'OAUTH_TOKEN_EXPIRED',
  OAUTH_SCOPE_MISMATCH = 'OAUTH_SCOPE_MISMATCH',
  OAUTH_REFRESH_FAILED = 'OAUTH_REFRESH_FAILED',
  OAUTH_CODE_EXCHANGE_FAILED = 'OAUTH_CODE_EXCHANGE_FAILED',
  OAUTH_NOT_INITIALIZED = 'OAUTH_NOT_INITIALIZED',

  // Zoho CRM Specific Errors
  ZOHO_API_ERROR = 'ZOHO_API_ERROR',
  ZOHO_RECORD_NOT_FOUND = 'ZOHO_RECORD_NOT_FOUND',
  ZOHO_DUPLICATE_RECORD = 'ZOHO_DUPLICATE_RECORD',
  ZOHO_INVALID_MODULE = 'ZOHO_INVALID_MODULE',
  ZOHO_MANDATORY_NOT_FOUND = 'ZOHO_MANDATORY_NOT_FOUND',
  ZOHO_RATE_LIMIT_EXCEEDED = 'ZOHO_RATE_LIMIT_EXCEEDED',
  ZOHO_UPSTREAM_UNAVAILABLE = 'ZOHO_UPSTREAM_UNAVAILABLE',
}
